### ISSUE TITLE
Describe how Ghetto algorithm works

### ISSUE THREAD

**Issue by hnykda** [fcurella/django-recommends#25]
Hello,

are there any sources how Ghetto alg works? I cannot find anything reliable and I would like to understand what is happening under the hood. 

Furthermore, recsys is quite obsolete (just for Python 2) and hence it would be great if we could use something modern, like scikit-learn. Would that be possible?

**Comment by fcurella** [comment]
Hi @hnykda 

The GhettoAlgorithm is adapted from: Segaran, T: Programming Collective Intelligence. I believe the book is under copyright, but the full relevant chapter seems to be available on [Google Scholar](https://books.google.com/books?id=fEsZ3Ey-Hq4C&lpg=PP1&dq=chapter%202%20Segaran%2C%20T%3A%20Programming%20Collective%20Intelligence&pg=PA7#v=onepage&q=chapter%202%20Segaran,%20T:%20Programming%20Collective%20Intelligence&f=false)

It's definitely possible to use scikit-learn, and I'd like to bundle a ready-to-use provider for that. I just need to find the time because I'm currently stretched pretty thin.

**Comment by hnykda** [comment]
Thank you for the answer!
